### ISSUE TITLE
Suggestion: autorestart Injector

### ISSUE THREAD

**Issue by yoksi** [rvazarkar/NGUInjector#77]
with so many added options which are constantly increasing, it becomes more often after time (or if you working with Injector more active) that some functions stop working correctly or get stuck with old settings

maybe add option for set automatic restart Injector after X hours?  and not important but upgrading simple unload option with quick restart possibility can be good

**Comment by player8472** [comment]
I'll write here, since its basically the same issue:
The process keeps running when exiting the injector via the GUI - would be nice if that could kill the process. 
Especially for updating the injector, so you don't have to quit the game and let the process crash (or alternatively search it in the taskmanager)

**Comment by rvazarkar** [comment]
@player8472 thats what the unload button on the main page is for.

**Comment by player8472** [comment]
lol, never saw that button...

**Comment by yoksi** [comment]
yes, but you don't always find out right away that something went wrong and sometimes it takes time for it to show up ... that's why I thought that some "autorefresh" "autorestart" would be nice
... with more functions and options added, more degeneration errors can occur more often also

**Comment by yoksi** [comment]
but probably all this is less important, it doesn't happen often
